name: dev
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gardenlinux/workflow-telemetry-action@6f19ac2411a52a120abb74c812592b44f165d05c # pin@v1
        with:
          metric_frequency: 1
          comment_on_pr: false
      - uses: actions/checkout@v3
      - name: build
        run: ./build
      - name: test
        run: ./test
