name: dev
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gardenlinux/workflow-telemetry-action@9742ad16c70308bc8fa5f850d6ee6b22f2cce076 # pin@v2
        with:
          metric_frequency: 1
          comment_on_pr: false
      - uses: actions/checkout@v5
      - name: build
        run: ./build
      - name: test
        run: ./test
